# Generated by Django 3.2.6 on 2021-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default=' ', max_length=200, null=True)),
                ('address', models.CharField(default=' ', max_length=200, null=True)),
                ('radius', models.CharField(default=' ', max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Coed', 'Coed')], default=' ', max_length=12, null=True)),
                ('hostel_name', models.CharField(default=' ', max_length=200, null=True)),
                ('cost_of_living', models.CharField(default=' ', max_length=20, null=True)),
                ('contact_number', models.CharField(default=' ', max_length=10, null=True)),
                ('map_link', models.CharField(default=' ', max_length=200, null=True)),
                ('hostel_img_1', models.ImageField(blank=True, default=' ', null=True, upload_to='images/')),
                ('hostel_img_2', models.ImageField(blank=True, default=' ', null=True, upload_to='images/')),
                ('hostel_img_3', models.ImageField(blank=True, default=' ', null=True, upload_to='images/')),
            ],
        ),
    ]
