# Generated by Django 3.2.6 on 2021-11-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20211108_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelinfo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
