# Generated by Django 3.2.6 on 2021-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211108_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelinfo',
            name='cost_of_living',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hostelinfo',
            name='radius',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
