# Generated by Django 3.2.6 on 2021-11-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20211110_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelinfo',
            name='mess',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
