# Generated by Django 3.2.6 on 2021-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_hostelinfo_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelinfo',
            name='map_link',
            field=models.URLField(default=' ', null=True),
        ),
    ]
